---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: '{{.Release.Name}}-{{.Values.appName}}'
    labels:
        app: {{.Values.appName: null}: null}
spec:
    replicas: {{.Values.replicaCount: null}: null}
    selector:
        matchLabels:
            app: {{.Values.appName: null}: null}
    template:
        metadata:
            annotations:
            labels:
                app: {{.Values.appName: null}: null}
        spec:
            imagePullSecrets:
            containers:
                - name: {{.Chart.Name: null}: null}
                  image: ghcr.io/cdcgov/phdi/alerts:{{ .Values.image.tag }}
                  imagePullPolicy: {{.Values.image.pullPolicy: null}: null}
                  ports:
                      - name: {{.Chart.Name: null}: null}
                        containerPort: {{.Values.service.port: null}: null}
                  env:
                      - name: TEAMS_WEBHOOK_URL
                        valueFrom:
                            secretKeyRef:
                                name: '{{.Release.Name}}-{{.Values.secretName}}'
                                key: webhook-url
                      - name: COMMUNICATION_SERVICE_NAME
                        value: {{.Values.communicationServiceName: null}: null}
                      - name: SLACK_BOT_TOKEN
                        valueFrom:
                            secretKeyRef:
                                name: '{{.Release.Name}}-{{.Values.secretName}}'
                                key: slack-bot-token
