apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-alerts-app
  labels:
    app: alerts-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: alerts-app
  template:
    metadata:
      annotations:
      labels:
        app: alerts-app
    spec:
      imagePullSecrets:
      containers:
        - name: {{ .Chart.Name }}
          image: ghcr.io/cdcgov/phdi/alerts:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.service.port }}
          env:
            - name: SMARTY_AUTH_ID
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-geocoding-secrets
                  key: auth-id
            - name: SMARTY_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-geocoding-secrets
                  key: token
