apiVersion: v1
kind: Secret
metadata:
  name: "{{.Release.Name}}-{{.Values.secretName}}"
type: Opaque
stringData:
  webhook-url: { { .Values.webhookUrl | quote } }
  slack-bot-token: { { .Values.slackBotToken | quote } }
