apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name}}-alerts-secrets
type: Opaque
stringData:
  webhook-url: {{ .Values.smartyAuthId | quote }}
  slack-bot-token: {{ .Values.slackBotToken | quote }}
