apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name}}-alerts-app"
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: alerts-app