---
replicaCount: 1

image:
    repository: ghcr.io/cdcgov/phdi/ecr-viewer
    pullPolicy: IfNotPresent
    tag: latest

service:
    port: 3000

# Will not work as written.
# These will need to be replaced by the equivalent secret values
databaseUrl: $database-connection-string

name: ecr-viewer
appName: ecr-viewer-app
secretName: ecr-viewer-secrets
serviceName: ecr-viewer-service
ecrViewerS3RoleArn: placeholder-arn
nbsPubKey: placeholder-key
ecrBucketName: placeholder-bucket
source: placeholder-source
