apiVersion: v1
kind: Service
metadata:
  name: record-linkage-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: record-linkage-app
