apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-message-parser-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: message-parser-app