apiVersion: v1
kind: Service
metadata:
  name: fhir-converter-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: fhir-converter-app
