---
replicaCount: 1

image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: 1.25.4

service:
    port: 80

# Will not work as written.
# These will need to be replaced by the equivalent Azure Key Vault values
databaseType: postgres
databasePassword: $password
databaseName: $dbName
databaseHost: $fqdn
databaseUser: postgres
databasePort: '5432'
patientTable: patient
personTable: person

appName: record-linkage-app
serviceName: record-linkage-service
