---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Release.Name }}-orchestration-app"
  labels:
    app: orchestration-app
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: orchestration-app
  template:
    metadata:
      annotations:
      labels:
        app: orchestration-app
    spec:
      imagePullSecrets:
      containers:
        - name: {{.Chart.Name}}
          image: ghcr.io/cdcgov/phdi/orchestration:{{ .Values.image.tag }}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - name: {{.Chart.Name | trunc 14}}
              containerPort: {{.Values.service.port}}
          env:
            - name: alerts-url
              valueFrom:
                secretKeyRef:
                  name: "{{.Release.Name}}-orchestration-secrets"
                  key: alerts-url
            - name: fhir-convertor-url
              valueFrom:
                secretKeyRef:
                  name: "{{.Release.Name}}-orchestration-secrets"
                  key: fhir-convertor-url
            - name: ingestion-url
              valueFrom:
                secretKeyRef:
                  name: "{{.Release.Name}}-orchestration-secrets"
                  key: ingestion-url
            - name: ingress-url
              valueFrom:
                secretKeyRef:
                  name: "{{.Release.Name}}-orchestration-secrets"
                  key: ingress-url
            - name: message-parser-url
              valueFrom:
                secretKeyRef:
                  name: "{{.Release.Name}}-orchestration-secrets"
                  key: message-parser-url
            - name: record-linkage-url
              valueFrom:
                secretKeyRef:
                  name: "{{.Release.Name}}-orchestration-secrets"
                  key: record-linkage-url
            - name: tabulation-url
              valueFrom:
                secretKeyRef:
                  name: "{{.Release.Name}}-orchestration-secrets"
                  key: tabulation-url
            - name: validation-url
              valueFrom:
                secretKeyRef:
                  name: "{{.Release.Name}}-orchestration-secrets"
                  key: validation-url