---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Release.Name }}-orchestration-app"
  labels:
    app: orchestration-app
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: orchestration-app
  template:
    metadata:
      annotations:
      labels:
        app: orchestration-app