---
apiVersion: v1
kind: Secret
metadata:
    name: '{{.Release.Name}}-orchestration-secrets'
type: Opaque
stringData:
    alerts-url: {{ .Values.alertsUrl | quote }}
    fhir-converter-url: {{ .Values.fhirConverterUrl | quote }}
    ingestion-url: {{ .Values.ingestionUrl | quote }}
    ingress-url: {{ .Values.ingressUrl | quote }}
    message-parser-url: {{ .Values.messageParserUrl | quote }}
    record-linkage-url: {{ .Values.recordLinkageUrl | quote }}
    tabulation-url: {{ .Values.tabulationUrl | quote }}
    validation-url: {{ .Values.validationUrl | quote }}
    ecr-bucket-name: {{ .Values.ecrBucketName | quote }}
