apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{.Values.appName}}"
  labels:
    app: {{.Values.appName}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
       app: {{.Values.appName}}
  template:
    metadata:
      annotations:
      labels:
        app: {{.Values.appName}}
    spec:
      serviceAccountName: ecr-viewer
      imagePullSecrets:
      containers:
        - name: {{.Chart.Name}}
          image: ghcr.io/cdcgov/phdi/ecr-viewer:{{ .Values.image.tag }}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - name: {{.Chart.Name}}
              containerPort: {{.Values.service.port}}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: "{{.Release.Name}}-{{.Values.secretName}}"
                  key: database-url
            - name: NBS_PUB_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{.Release.Name}}-{{.Values.secretName}}"
                  key: nbs-pub-key
