---
apiVersion: v1
kind: Secret
metadata:
    name: '{{.Release.Name}}-{{.Values.secretName}}'
type: Opaque
stringData:
    database-url: {{.Values.databaseUrl | quote }}
    nbs-pub-key: {{.Values.nbsPubKey | quote }}
    ecr-bucket-name: {{.Values.ecrBucketName | quote }}
    next-public-source: {{.Values.nextPublicSource | quote }}
