apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tabulation-app
  labels:
    app: tabulation-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tabulation-app
  template:
    metadata:
      annotations:
      labels:
        app: tabulation-app
    spec:
      imagePullSecrets:
      containers:
        - name: {{ .Chart.Name }}
          image: ghcr.io/cdcgov/phdi/tabulation:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.service.port }}
          env:
            - name: fhir_url
              value: {{ .Values.fhirUrl }}
            - name: cred_manager
              value: {{ .Values.credManager }}