---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress
    annotations:
        kubernetes.io/ingress.class: azure/application-gateway
        appgw.ingress.kubernetes.io/backend-path-prefix: /
        cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
    tls:
        - hosts:
              - {{.Values.ingressHostname }}
          secretName: phdi-playground-issuer-account-key
    rules:
        - host: {{.Values.ingressHostname }}
          http:
              paths:
                  - path: /ingestion/*
                    pathType: Prefix
                    backend:
                        service:
                            name: {{.Values.ingestionServiceName }}
                            port:
                                number: 8080
                  - path: /alerts/*
                    pathType: Prefix
                    backend:
                        service:
                            name: {{.Values.alertsServiceName }}
                            port:
                                number: 8080
                  - path: /fhir-converter/*
                    pathType: Prefix
                    backend:
                        service:
                            name: {{.Values.fhirConverterServiceName }}
                            port:
                                number: 8080
                  - path: /message-parser/*
                    pathType: Prefix
                    backend:
                        service:
                            name: {{.Values.messageParserServiceName }}
                            port:
                                number: 8080
                  - path: /record-linkage/*
                    pathType: Prefix
                    backend:
                        service:
                            name: {{.Values.recordLinkageServiceName }}
                            port:
                                number: 8080
                  - path: /tabulation/*
                    pathType: Prefix
                    backend:
                        service:
                            name: {{.Values.tabulationServiceName }}
                            port:
                                number: 8080
                  - path: /validation/*
                    pathType: Prefix
                    backend:
                        service:
                            name: {{.Values.validationServiceName }}
                            port:
                                number: 8080
                  - path: /orchestration/*
                    pathType: Prefix
                    backend:
                        service:
                            name: {{.Values.orchestrationServiceName }}
                            port:
                                number: 8080
                  - path: /ecr-viewer/*
                    pathType: Prefix
                    backend:
                        service:
                            name: {{.Values.ecrViewerServiceName }}
                            port:
                                number: 8080
