---
apiVersion: v2
name: validation-chart
description: A Helm chart for the DIBBs Validation Service
type: application
version: 0.1.7
appVersion: 1.2
icon: https://commons.wikimedia.org/wiki/File:US_CDC_logo.svg
