apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Release.Name}}-{{.Values.appName}}"
  labels:
    app: {{.Values.appName}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.appName}}
  template:
    metadata:
      annotations:
      labels:
        app: {{.Values.appName}}
    spec:
      imagePullSecrets:
      containers:
        - name: {{.Chart.Name}}
          image: ghcr.io/cdcgov/phdi/{{.Values.name}}:{{.Values.image.tag}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - name: {{.Chart.Name | trunc 15}}
              containerPort: {{.Values.service.port}}
          env:
            - name: fhir_url
              value: {{.Values.fhirUrl}}
            - name: cred_manager
              value: {{.Values.credManager}}
            - name: DATABASE_URL
              value: {{.Values.databaseConnectionString}}
      initContainers:
        - name: flyway
          image: ghcr.io/cdcgov/phdi/{{.Values.name}}-flyway:{{.Values.image.tag}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          args: ["-schemas=public", "-connectRetries=10", "-url={{.Values.jdbcDatabaseUrl}}", "-user={{.Values.jdbcDatabaseUser}}", "-password={{.Values.jdbcDatabasePassword}}", "-locations=filesystem:/flyway/sql", "migrate"]
