apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-validation-app
  labels:
    app: validation-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: validation-app
  template:
    metadata:
      annotations:
      labels:
        app: validation-app
    spec:
      imagePullSecrets:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.service.port }}
