replicaCount: 1

image:
  repository: ghcr.io/cdcgov/phdi/alerts
  pullPolicy: IfNotPresent
  tag: "v1.0.9"

service:
  port: 8080

webhookUrl: "$webhookUrl"
slackBotToken: "$slackBotToken"
communicationServiceName: "$commServiceName"
