replicaCount: 1

image:
  repository: ghcr.io/cdcgov/phdi/alerts
  pullPolicy: IfNotPresent
  tag: latest

service:
  port: 8080

webhookUrl: "$webhookUrl"
slackBotToken: "$slackBotToken"
communicationServiceName: "$commServiceName"

name: "alerts"
appName: "alerts-app"
secretName: "alerts-secrets"
serviceName: "alerts-service"
