name: Release Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      versionNumber:
        description: "Set chart version"
        required: true
        type: string

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Modify files with script
        run: |
          # Execute a custom script
          python ./.github/config/modify_files.py ./charts ${{ github.event.inputs.versionNumber }}

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
            config: ./.github/config/cr.yml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
