---
name: Updates Chart Version


on:
    repository_dispatch:
        types: [trigger-workflow]

permissions:
    id-token: write
    contents: write
    packages: write
    pull-requests: write
jobs:
    update-chart-version:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4


            - name: Extract Service Name & Version
              run: |
                  # Parse the service name from the payload
                  service_name=${{ github.event.client_payload.service }}
                  echo "Service Name: $service_name"

                  # Parse the version from the payload
                  version=${{ github.event.client_payload.version }}
                  echo "Version: $version"

            - name: Set up Python (for yq)
              uses: actions/setup-python@v4
              with:
                  python-version: '3.8'

            - name: Install yq
              run: pip install yq semver

            - name: Get current chart version
              id: get-version
              run: |
                  CURRENT_VERSION=$(yq '.version' charts/tefca-viewer/Chart.yaml)
                  echo "Current Chart Version: $CURRENT_VERSION"
                  echo "current_version=$CURRENT_VERSION" >> $GITHUB_ENV

            - name: Increment chart version
              id: increment-version
              run: |
                  VERSION_PART=${{ github.event.inputs.bump_patch || 'patch' }}
                  echo "Debug: env.current_version=${{ env.current_version }}"  # Debug log
                  NEW_VERSION=$(python -c "from semver import VersionInfo as V; print(V.parse('${{ env.current_version }}').bump_${VERSION_PART}())")
                  echo "New Chart Version: $NEW_VERSION"
                  echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

            - name: Update Chart.yaml
              run: |
                  yq -i -y ".version = \"${{ env.new_version }}\"" charts/tefca-viewer/Chart.yaml
                  cat charts/tefca-viewer/Chart.yaml


            - name: Create a Pull request to main
              run: |
                  # Set the required variables
                  repo_owner="CDCgov"
                  repo_name="phdi-charts"


                  curl -L \
                   -X POST \
                   -H "Authorization: : Bearer ${{ secrets.GITHUB_TOKEN }}" \
                   -H "Accept: application/vnd.github+json" \
                   -H "X-GitHub-Api-Version: 2022-11-28" \
                   https://api.github.com/repos/$repo_owner/$repo_name/pulls \
                   -d '{
                     "title": "Bump chart version-${{ env.new_version }}",
                     "head": "feature-branch",
                     "base": "main",
                    "body": "Automated changes by Deploy Query Connector to demo site workflow."
                     }'
